apiVersion: v1
kind: Namespace
metadata:
  name: botbot
---
apiVersion: v1
kind: Secret
metadata:
  namespace: botbot
  name: botbot
type: Opaque
data:
  OPENAI_API_KEY: <base64 encoded key>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: botbot
  name: botbot
  labels:
    app: botbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: botbot
  template:
    metadata:
      labels:
        app: botbot
    spec:
      containers:
        - name: botbot
          image: <docker user>/botbot:latest
          resources: {}
          ports:
            - containerPort: 3000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: botbot
                  key: OPENAI_API_KEY
---
kind: Service
apiVersion: v1
metadata:
  namespace: botbot
  name: botbot
  labels:
    app: botbot
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: botbot
  type: ClusterIP
